### ISSUE TITLE
Implement multi-language strings like in CoverageJSON

### ISSUE THREAD

**Issue by dmitry-brizhinev** [ANU-Linked-Earth-Data/ontology#12]

**Comment by qxcv** [comment]
RDF should have this built-in, shouldn't it? Like `foo:bar spam:ham "Je suis une grenouille"@fr .`.

**Comment by dmitry-brizhinev** [comment]
RDF lets you tag strings with their language, but the CoverageJSON feature I'm talking about is that any place where you can put a string you can instead put an object consisting of multiple strings in different languages

**Comment by qxcv** [comment]
That's what I mean.

``` turtle
:myDataset a qb:DataSet ;
    # English & pig Latin labels
    rdfs:label "A dataset"@en ;
    rdfs:label "A etdatasay"@pl .
```

**Comment by dmitry-brizhinev** [comment]
Oh yeah, I guess that would work, as long as I don't add any "max 1" constraints to the labels
